// Generates an MD3 dark color scheme from the bot's existing Catppuccin Mauve
// brand color (src/config.js COLORS.mauve, 0xcba6f7). Run manually whenever
// that seed changes:
//
//   npm run generate-theme
//
// This is dev-tooling only. The output below gets pasted by hand into the
// :root block of src/web/style.css. Nothing in the running dashboard imports
// this file or @material/material-color-utilities at runtime.
//
// Scheme choice: SchemeTonalSpot, not SchemeExpressive. SchemeExpressive is
// documented (see its own source, scheme_expressive.js) as "intentionally
// detached from the source color" and literally rotates the primary palette
// hue by +240 degrees before generating tones. Run this seed through it and
// primary comes out teal, not anywhere near mauve. That would put the web
// dashboard's brand color at odds with every embed and custom emoji the bot
// renders on the Discord side. TonalSpot keeps primary anchored close to the
// seed hue, which is what "one consistent brand" actually requires. The
// Expressive *look* still comes through in style.css via the wider shape
// scale (large-increased/extra-large-increased/extra-extra-large), the
// motion easing/duration tokens, and the full type scale - those don't have
// a seed-fidelity tradeoff the way color does.
import {
  Hct,
  SchemeTonalSpot,
  MaterialDynamicColors,
  customColor,
  hexFromArgb,
  argbFromHex,
} from '@material/material-color-utilities';

const SEED_HEX = '#cba6f7'; // Catppuccin Mauve, src/config.js COLORS.mauve
const SUCCESS_SEED_HEX = '#a6e3a1'; // Catppuccin Green, src/config.js COLORS.green

const ROLES = [
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer', 'inversePrimary',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'background', 'onBackground', 'surface', 'onSurface',
  'surfaceVariant', 'onSurfaceVariant',
  'surfaceContainerLowest', 'surfaceContainerLow', 'surfaceContainer',
  'surfaceContainerHigh', 'surfaceContainerHighest',
  'outline', 'outlineVariant', 'inverseSurface', 'inverseOnSurface',
];

// kebab-case to match --md-sys-color-* naming
function toKebab(name) {
  return name.replace(/([A-Z])/g, '-$1').toLowerCase();
}

const seedHct = Hct.fromInt(argbFromHex(SEED_HEX));
const scheme = new SchemeTonalSpot(seedHct, /* isDark */ true, /* contrastLevel */ 0.0);

console.log(`/* Generated by scripts/generate-theme.mjs from seed ${SEED_HEX} (Catppuccin Mauve). */`);
console.log(`/* SchemeTonalSpot, dark, contrast 0.0. Paste into style.css :root. */`);
for (const role of ROLES) {
  const dynamicColor = MaterialDynamicColors[role];
  const hex = hexFromArgb(dynamicColor.getArgb(scheme));
  console.log(`  --md-sys-color-${toKebab(role)}: ${hex};`);
}

// MD3's base 5 roles (primary/secondary/tertiary/error/neutral) have no
// "success" concept. The bot uses Catppuccin green for success everywhere
// on the Discord side (config confirmations, ticket resolution, session-vote
// opened, all via COLORS.green in src/config.js). Reusing tertiary-container
// for a dashboard "success" flash would be MD3-token-correct but
// semantically wrong, tertiary here renders as a muted rose that reads as
// a warning, not a confirmation, and would be the one color on the
// dashboard that does not match its Discord-side meaning. customColor()
// generates a properly tonal-paired role from the green seed, blended
// toward the primary hue for harmony rather than a jarring pure green.
const successGroup = customColor(argbFromHex(SEED_HEX), {
  value: argbFromHex(SUCCESS_SEED_HEX),
  name: 'success',
  blend: true,
}).dark;
console.log(`  --md-sys-color-success: ${hexFromArgb(successGroup.color)};`);
console.log(`  --md-sys-color-on-success: ${hexFromArgb(successGroup.onColor)};`);
console.log(`  --md-sys-color-success-container: ${hexFromArgb(successGroup.colorContainer)};`);
console.log(`  --md-sys-color-on-success-container: ${hexFromArgb(successGroup.onColorContainer)};`);
